// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpQGSJc27LOPeQi00ApVQO0oMfY6vh7A',
    appId: '1:74368097917:web:38479588a11095796b1b14',
    messagingSenderId: '74368097917',
    projectId: 'homehero-5f32f',
    authDomain: 'homehero-5f32f.firebaseapp.com',
    storageBucket: 'homehero-5f32f.firebasestorage.app',
    measurementId: 'G-5R70CV3QXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRUAkWmtHSgKJrRh6jVMYSKY0vT7LIA-s',
    appId: '1:74368097917:android:893c525baf272cfc6b1b14',
    messagingSenderId: '74368097917',
    projectId: 'homehero-5f32f',
    storageBucket: 'homehero-5f32f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cNwtcuSMdUThmyPVfyxIOgHcrcnEiLY',
    appId: '1:74368097917:ios:f9702cfba326e9256b1b14',
    messagingSenderId: '74368097917',
    projectId: 'homehero-5f32f',
    storageBucket: 'homehero-5f32f.firebasestorage.app',
    iosBundleId: 'com.homehero.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6cNwtcuSMdUThmyPVfyxIOgHcrcnEiLY',
    appId: '1:74368097917:ios:f9702cfba326e9256b1b14',
    messagingSenderId: '74368097917',
    projectId: 'homehero-5f32f',
    storageBucket: 'homehero-5f32f.firebasestorage.app',
    iosBundleId: 'com.homehero.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpQGSJc27LOPeQi00ApVQO0oMfY6vh7A',
    appId: '1:74368097917:web:45698409b3d183076b1b14',
    messagingSenderId: '74368097917',
    projectId: 'homehero-5f32f',
    authDomain: 'homehero-5f32f.firebaseapp.com',
    storageBucket: 'homehero-5f32f.firebasestorage.app',
    measurementId: 'G-XFGLXLXJ9W',
  );
}
